sudo: false

langurage: python

matrix:
  - python: 3.7
    dist: xenial
    os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7

install:
  - pip install pytest

script:
  - py.test test_sample.py
